name: Linux Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Linux Release
    runs-on: ubuntu-latest
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
      - name: apt-get install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgmp-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev freeglut3-dev libglfw3-dev libxxf86vm-dev
      - name: Setup Haskell
        id: setup-haskell-stack
        uses: haskell/actions/setup@v1.2
        with:
          ghc-version: 8.6.5
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
      - name: Build
        run: ./scripts/build-nix.sh
      - uses: actions/cache@v2
        with:
          path: ./.stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('./stack.yaml.lock') }}
          restore-keys: ${{ runner.os }}-stack-
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./improviz-nix-*.tar.gz
          asset_name: improviz-nix-tar.gz
