name: Tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    name: Testing ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: apt-get update
        run: sudo apt-get update
      - name: apt-get install dependencies
        run: sudo apt-get install freeglut3-dev libglfw3-dev
      - name: Setup Haskell
        id: setup-haskell-stack
        uses: haskell/actions/setup@v1.2
        with:
          ghc-version: 8.6.5
          enable-stack: true
          stack-version: 'latest'
      - uses: actions/cache@v2
        with:
          path: ./.stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('./stack.yaml.lock') }}
          restore-keys: ${{ runner.os }}-stack-

      - run: stack test
